apiVersion: apps/v1
kind: Deployment
metadata:
  name: application-deployment
spec:
  selector:
    matchLabels:
      app: sbk-remote-debug
  template:
    metadata:
      labels:
        app: sbk-remote-debug
    spec:
      containers:
        - image: rkbdocker/springboot-kubernetes-remote-debug
          imagePullPolicy: Always
          name: sbk-remote-debug
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: debug-port
              containerPort: 5005
              protocol: TCP
          env:
            - name: JAVA_TOOL_OPTIONS
              value: '-Xdebug -agentlib:jdwp=transport=dt_socket,address=0.0.0.0:5005,server=y,suspend=n'
      imagePullSecrets:
        - name: myregistrykey