kind: Service 
apiVersion: v1 
metadata:
  name: sbk-remote-debug-service 
spec:
  type: NodePort
  selector:
    app: sbk-remote-debug 
  ports:
    - nodePort: 30163
      port: 8080 
      targetPort: 8080